openapi: 3.0.1
info:
  title: Diet-Tracker
  version: 1.0.0
servers:
- url: //localhost/api
tags:
- name: Product
  description: Product endpoints
- name: Meal
  description: User meals
paths:
  /api/product:
    get:
      tags:
      - Product
      summary: Get product by name
      parameters:
      - name: name
        in: query
        description: Product name to find in database
        required: true
        schema:
          type: string
      responses:
        200:
          description: Ok
        404:
          description: Not found
    post:
      tags:
      - Product
      summary: Add a new product to database
      description: This can be done by user with admin role
      requestBody:
        description: Product object that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        200:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Invaild user role
      security:
      - Bearer: []
  /api/product/{id}:
    delete:
      tags:
      - Product
      summary: Delete product
      description: This can be done by user with admin role
      parameters:
      - name: id
        in: path
        description: The id of product
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Deleted
        401:
          description: Unauthorized
        403:
          description: Invaild user role
        404:
          description: Product not found
      security:
      - Bearer: []
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        barcode:
          type: string
        proteins:
          type: number
          format: float
        carbs:
          type: number
          format: float
        fats:
          type: number
          format: float
        kcal:
          type: number
          format: float
        volume:
          type: number
          format: float
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: token
      
