swagger: "2.0"
info:
  version: "1.0.0"
  title: "Diet-Tracker"

host: "localhost"
basePath: "/api"
tags:
- name: "Product"
  description: "Product endpoints"
- name: "Meal"
  description: "User meals"
paths:
  /api/product:
    post:
      tags:
      - "Product"
      summary: "Add a new product to database"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Created"
          

